services:
    dev:
        build:
#            context: ./docker
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - './:/app'
        command: 'tail -f /dev/null'
    web-server:
        build:
            context: ./docker/sail
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        working_dir: '/var/www/html'
        volumes:
            - '.:/var/www/html'
